dir:
  img_dir: "/workspace/data/hmi_jpgs_512"
  index_dir: "./training/data_split"
  save_dir: "./results"
  train_p: ["24image_reg_P1.csv", "24image_reg_P2.csv"]
  cal_p: ["24image_reg_P3.csv"]
  test_p: ["24image_reg_P4.csv"]

cuda:
  device: 0 #[0, 1]

model:
  name: "Resnet152"
  mode: "cp"
  dropout: 0.5

scheduler:
  max_lr: 0.0001
  div_factor: 10000
  epochs: 50

optimize:
  lr: 0.001
  batch_size: 16
  wt_decay: [0, 0.01, 0.001, 0.0001]