dir:
  img_dir: "/workspace/data/hmi_jpgs_512"
  index_dir: "./training/data_split"
  save_dir: "./results"

cuda:
  device: [0, 1]

model:
  name: "Resnet18"
  mode: "cp"
  dropout: 0.5

scheduler:
  max_lr: 0.0001
  div_factor: 100000
  epochs: 50

optimize:
  lr: 0.001
  batch_size: 16
  wt_decay: [0, 0.01, 0.001, 0.0001]